//for requesting
export const REQUEST_USERS_DATA='REQUEST_USERS_DATA'

//for response

export const REQUEST_USERS_RESPONSE='REQUEST_USERS_RESPONSE'

//-------------create new----------
export const USERS_POST_REQUEST='USERS_POST_REQUEST'
export const USERS_POST_RESPONSE='USERS_POST_RESPONSE'

export const DELETE_USER_REQUEST='DELETE_USER_REQUEST'
export const DELETE_USER_RESPONSE='DELETE_USER_RESPONSE'

export const EDIT_USER_REQUEST='EDIT_USER_REQUEST'
export const EDIT_USER_RESPONSE='EDIT_USER_RESPONSE'

export const REQUEST_USER_BYID='REQUEST_USER_BYID'
export const RESPONSE_OF_USER_BYID='RESPONSE_OF_USER_BYID'
